WIP: Add locales provides
Cardinal-Invariants/quest-creator-mobile pull request #2
Opened 2020-10-04 21:26 UTC by Qwebeck

Нужно ещё доработать скрипт, но пока что посмотрите на то что есть и пооставляйте свои отзывы и внимания, если найдуться

2020-10-05 18:18 UTC, Qwebeck commented on .vscode/settings.json
> +{
Я думаю что не помешает если у нас будет общий линтинг для пайтона.

2020-10-05 18:23 UTC, Qwebeck commented on lib/screens/home_screen/home_screen.localizations.dart
> +import 'package:flutter/material.dart';
Предлагаю такой концепт создания виджетов: 
Есть экран, который состоит из компонентов. ( в этом случае `home_scrceen` )
Экран находиться в пакете с таким же названием как он: (`home_scrceen/`home_scrceen`)
В том же пакете что и экран, находиться файл с переводами для всех виджетов, которые находяться на экране. Название файла должно быть `[screen_name].localizations`

Эти конвенции важные, потому что потом, на основании них, скрипт в пайтоне будет облегчать нам создание переводов.

Что вы думаете о такой концепции ?

2020-10-05 18:25 UTC, Qwebeck commented on lib/screens/home_screen/home_screen.localizations.dart
> +  static HomeScreenLocalizations of(BuildContext context) {
На этот клас можно смотреть как на Enum, который содержит в себе ключ и перевод. Используем подобную вещь, потому что благодаря ней, в будущем будет проще сменить язык в проекте

2020-10-05 18:25 UTC, Qwebeck commented on lib/screens/home_screen/l10n/intl_messages.arb
> +{
Автосгенерированое сообщение

2020-10-05 18:26 UTC, Qwebeck commented on lib/screens/home_screen/l10n/intl_pl.arb
> +{
Перевод который должны делать мы на основании файла `intl_messages.arb`
Название файла должно быть 
`intl_[locale].arb`

2020-10-05 18:27 UTC, Qwebeck commented on lib/scripts/generate_translations.py
> +import argparse
Скрипт который позволяет генерировать переводы к файлам

2020-10-05 18:28 UTC, Qwebeck commented
https://flutter.dev/docs/development/accessibility-and-localization/internationalization

2020-10-08 17:25 UTC, VVlovsky requested changes

2020-10-08 17:25 UTC, VVlovsky commented on .vscode/settings.json
> +{
Я бы добавил эту папку в игнор, т.к. считаю, что переменные среды не должны находится в проекте. Более того, не все используют vscode.

2020-10-08 17:25 UTC, VVlovsky commented on lib/main.dart
> +class QuestCreator extends StatelessWidget {
Предлагаю вынести этот класс в отдельный файл.

2020-10-08 17:25 UTC, VVlovsky commented on lib/screens/home_screen/home_screen.localizations.dart
> +import 'package:flutter/material.dart';
Не возражаю)

2020-10-08 17:31 UTC, VVlovsky requested changes
Стоило бы убрать файлы среды с проекта и вынести имплементацию виджетов с мейна.

2020-10-10 10:53 UTC, Qwebeck commented on lib/main.dart
> +class QuestCreator extends StatelessWidget {
А стоит ли ? 
Тогда файл `main` будет состоять только из 3 линий 
```
void main() {
 runApp(QuestCreator());
}
```
И получаеться какой-то немного бесполезный файл. По-моему лучше так как сейчас. @VVlovsky  , что ты об этом думешь ?

2020-10-10 10:58 UTC, Qwebeck commented on .vscode/settings.json
> +{
Может быть полезно иметь папку с настройками каждого едитора потому что тогда у всех будет одинаковый код и это будет более читабельно. (как например здесь https://github.com/angular/angular) Но в этом случае действительно не имеет смысла потому что у нас будет очень мало пайтона.

2020-10-10 12:24 UTC, VVlovsky commented on lib/main.dart
> +class QuestCreator extends StatelessWidget {
main.dart своего рода инициализация, каждый же важный виджет удобнее и читабельнее хранить в отдельном для него файле с соответствующим именем. Впрочем, для нас 4ых это не будет иметь особого значения.

2020-10-10 12:26 UTC, VVlovsky approved these changes

2020-10-10 12:43 UTC, merged